baseURL = "https://lokal.ninja/saarland"
languageCode = "de-DE"
title = "Lokal Ninja - Saarland"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Saarland"
  repo = "saarland"
